### ISSUE TITLE
[FIXED] Make it ready to use

### ISSUE THREAD

**Issue by sergeevabc** [vkaldi/keepass-diceware#1]
Dear Mr. Kaldi,
Could you be so kind to publish Keepass-Diceware plugin as ```.plgx```?

**Comment by vkaldi** [comment]
Unfortunately, keepass only supports C# (.csproj) projects as a source for plgx.  
This is an F# project.

**Comment by sergeevabc** [comment]
So… how to use it with Keepass then?

**Comment by vkaldi** [comment]
Keepass comes with two options to run plugins:  

1. "Packing" sources into plgx file using "--plgx-create" switch.  Keepass then unpacks that file and compiles the plugin itself (by running something equivalent to "msbuild plugin.csproj".  This only supports C# projects.    
2. Compiling the plugin by yourself and copying the *.dll file into Keepass directory.  

https://keepass.info/help/v2_dev/plg_index.html#plgx  

I currently have no plans to include the compiled *.dll as a part of the source on github.    
But, here are the necessary files, copied from my machine, no guarantee and/or warranty.  
[keepass-diceware.zip](https://github.com/vkaldi/keepass-diceware/files/1500237/keepass-diceware.zip)
Dump them into your keepass directory and you will have "Diceware passphrase generator" available on password generator screen under custom algorithms.

**Comment by sergeevabc** [comment]
@vkaldi, thank you, it works as expected, however I’m a bit confused about dictionary you used
```
dodo.53.vera.ww.qw.yw.nasal
```

**Comment by vkaldi** [comment]
It's the standard diceware dictionary, as available on http://world.std.com/%7Ereinhold/diceware.html.  
I just embedded it directly into dll (https://github.com/vkaldi/keepass-diceware/blob/master/Plugin/wordlist.txt).
